### ISSUE TITLE
PouchDB 3.0 is out.  Remove warning from the README

### ISSUE THREAD

**Issue by MichaelJCole** [pouchdb/express-pouchdb#121]
http://pouchdb.com/2014/08/12/pouchdb-3.0.0.html

Check dependencies and example code in the readme.  Remove the warning.

**Comment by marten-de-vries** [comment]
Done in #162.

**Comment by marten-de-vries** [comment]
Fixed in 29c016b28d93b7dad52d0df5a35bea6ec493da29
