### ISSUE TITLE
Fauxton should not hang it's sub-directories in the DB namespace

### ISSUE THREAD

**Issue by yaronyg** [pouchdb/express-pouchdb#131]
Right now Fauxton hangs the js, css, img and fonts directory off root. Which means that if one wanted a DB with any of those names it wouldn't work. We either need to change the names to be things that aren't legal DB names (prefixing with _ works) or we should move them to live under _utils.

**Comment by nolanlawson** [comment]
This issue was moved to pouchdb/pouchdb-server#174
