### ISSUE TITLE
/_config api accepts every valid JSON value

### ISSUE THREAD

**Issue by marten-de-vries** [pouchdb/express-pouchdb#157]
Currently /_config parses every value it gets as JSON. CouchDB only accepts the JSON string, though. Also the other api's (/_config/section/key, /_config/section) only return strings as values, even for booleans/numbers. In other words, the strings are part of the internal data model. express-pouchdb/pouchdb-server need to be fixed accordingly.

This actually becomes a problem when Fauxton PUTs the string "false" which is truthy in JS.

Since our config file is json, people are bound to put json values in it. The best way to handle this is probably by converting them to strings on start (at the same time as the hashing of the admin passwords).

**Comment by marten-de-vries** [comment]
Fixed: 3d5cfbc4cb03c8dc53d3f0a3659366a1b1a7ebeb

**Comment by nolanlawson** [comment]
LGTM. Agree with the solution
