### ISSUE TITLE
Support for viewCleanup()

### ISSUE THREAD

**Issue by mshick** [pouchdb/express-pouchdb#165]
It doesn't look like this is currently supported, but would be good to have. Hopefully it just needs a route. 

http://pouchdb.com/api.html#view_cleanup

**Comment by nolanlawson** [comment]
fixed by a5403af54bb5b5d3eded9134597365e9b404dc4b

**Comment by marten-de-vries** [comment]
Actually, since view cleanup is not really compaction, does it make sense to move it into a separate file so it can be enabled/disabled independently? If so, I can open a follow-up PR.

**Comment by nolanlawson** [comment]
Yes, it's not "true" compaction. However it's pretty fundamental for map/reduce, so I don't know if it should be disableable independently.

**Comment by marten-de-vries** [comment]
You can currently disable mapreduce (/_view & /_temp_view) if you don't need it. You can currently also disable /_compact if you don't need it. But you can't disable /_compact without disabling /_view_cleanup.

It might be a granularity that's not often needed, but it's there for pretty much everything else so at least for the sake of consistency it's nice to have.

**Comment by nolanlawson** [comment]
OK, sounds reasonable.

**Comment by mshick** [comment]
Thanks for running with this. Glad I could help get the feature going.

**Comment by nolanlawson** [comment]
Sure, thanks for the help!
