### ISSUE TITLE
Implement couchperuser

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/express-pouchdb#199]
Looks like it might actually get included in Couch core. In any case, it would be a great feature for PouchDB Server, and there are shell-based unit tests that we can use to confirm that we implemented it correctly: https://issues.apache.org/jira/browse/COUCHDB-2191

**Comment by tohagan** [comment]
+1

**Comment by nolanlawson** [comment]
This issue was moved to pouchdb/pouchdb-server#176
