### ISSUE TITLE
API read only, unless admin

### ISSUE THREAD

**Issue by stephenkeep** [pouchdb/express-pouchdb#201]
Hi Guys,

I have a scenerio where I would like all the benefits of couchdb sync but I dont want the clients to write data to the db. Only the server will be updating the db.

Im new to couchdb and im not sure how to set this up in a secure way so that the API is locked down to read only. Can you point me in the right direction please?

Cheers

**Comment by nickcolley** [comment]
Hey @stephenkeep!

@nolanlawson has written up some patterns over at https://github.com/nolanlawson/pouchdb-authentication#couchdb-authentication-recipes that might help you.

**Comment by stephenkeep** [comment]
Excellent thanks nick I'll check it out :)

**Comment by nolanlawson** [comment]
This issue was moved to pouchdb/pouchdb-server#177
