### ISSUE TITLE
couchdb supports POST on views, express-pouchdb does not

### ISSUE THREAD

**Issue by robotlovesyou** [pouchdb/express-pouchdb#215]
Couchdb supports POST requests for views. (i.e. `/dbname/_design/designDocName/_view/viewName`) but express-pouchdb only supports GET.

I cam across this because the nano library takes advantage of this when the 'keys' query option is used. 

Pull request with a fix for this is incoming.

**Comment by marten-de-vries** [comment]
PR merged (#216): 401689275c50b225bfb4568cc0b59bf09d2b4be4

Thanks for reporting & fixing.
