### ISSUE TITLE
How can I define a `validate_doc_update` function?

### ISSUE THREAD

**Issue by bguiz** [pouchdb/express-pouchdb#228]
I have tried looking for how to add a [validation function](http://guide.couchdb.org/draft/validation.html), but haven't yet found any reference apart from #69 which indicates that support has been added.

CC @marten-de-vries @nolanlawson 

Also, I am assuming that if using `express-pouchdb` on the server, I can simply ignore [this issue](https://github.com/pouchdb/pouchdb/issues/1412).

**Comment by nolanlawson** [comment]
You should be able to add it by just PUTing a _design document with what you want.

Here's creating the design doc:

![screenshot 2015-07-26 23 20 34](https://cloud.githubusercontent.com/assets/283842/8898090/035e5668-33ed-11e5-86b2-9c2dc0e231f8.png)

And here's an invalid doc throwing an error:

![screenshot 2015-07-26 23 20 50](https://cloud.githubusercontent.com/assets/283842/8898091/0b728b44-33ed-11e5-87c4-73c5b3819853.png)

Does that make sense? It should work exactly the same as CouchDB (hopefully!).

**Comment by bguiz** [comment]
I see that you have used `_design/mydoc`, and I have also found this
that `pouchdb-validation` is a dependency of `pouchdb-express`,
so [its documentation](http://pythonhosted.org/Python-PouchDB/js-plugins.html#pouchdb-validation-plug-in)
is probably what I am looking for.

In its example, it uses `_design/test`. Am I safe to assume that I I
can set `_id` to anything I like, so long as it starts with
`_design/`?
Otherwise how should I derive the value of `_id`?

Also, can I assume that the JS code in the example will work without
`python-pouchdb-js`?

(Sorry if this is a n00b question)
W: http://bguiz.com

**Comment by nolanlawson** [comment]
Yep, `_design/foo` will work just as well. And yeah, python-pouchdb is just the repo that @marten-de-vries uses to host his code, but it's not necessarily Python-related.

**Comment by bguiz** [comment]
Got it working now - thanks for the very detailed reply!



W: http://bguiz.com
