### ISSUE TITLE
Where would I put in a filter on all reads (GETs)?

### ISSUE THREAD

**Issue by bguiz** [pouchdb/express-pouchdb#230]
I have reviewed the various couchdb authentication recipes on @nolanlawson 's `pouchdb-authentication` project. [This one](https://github.com/nolanlawson/pouchdb-authentication#some-people-can-read-some-docs-some-people-can-write-those-same-docs) seems the closest to what I need to do, but not quite:

I need users to be able to write documents, and have only some other users be able to read the documents. Not based on roles, but based on custom logic. For example user A wants some of his documents to only be read by user B, and some of his other documents to only be read by users C and D. User A may later change his mind about who gets to read which documents.

In any case, this leads down a rabbit hole about per-document read authorisation:
- recommend per-user databases (won't work for above scenario)
- [per doc read access control logic (ACL)](http://wiki.apache.org/couchdb/PerDocumentAuthorization)
- [why CouchDB is reluctant to enable a `validate_doc_read` even though a `validate_doc_update` is available](http://mail-archives.apache.org/mod_mbox/couchdb-dev/201010.mbox/%3CC4B01815-5A28-4E5F-975D-70344B7570EC@apache.org%3E)

So, it seems unlikely that this could be solved at a CouchDB level.

However, my thoughts are that when using `express-pouchdb` in conjunction with [pouchdb-authentication](https://github.com/nolanlawson/pouchdb-authentication), I don't see anything preventing this from happening at an `express` level - it could fit in neatly as middleware attached to express routes.

Questions:
- On a server using `express` with `express-pouchdb`, would it be possible to add a middleware on any `GET` operations on that exposes the database, e.g. `/db`?
- If so, how would we go about obtaining the `userCtx`, in a format similar to `validate_doc_update`?

**Comment by bguiz** [comment]
By adding cookie parse, and a custom middleware, i was able to get an `AuthSession` string like so:

```
server.use('/db',
  cookieParser(),
  filterDbGetMiddleware,
  expressPouchDbApplication);

function filterDbGetMiddleware(req, res, next) {
  if (req.method === 'GET') {
    if (req.path.split('_')[0] === '/app/foo') {
      console.log(req.method, req.path);
      console.log('cookies', req.cookies);
    }
  }
  next();
}
```

Yields the following output:

```
GET /app/foo_123
cookies { AuthSession: 'fa464c03-1be4-4d90-acb6-7dfb707047bb' }
```

From the value of the `AuthSession`, the next step would be to obtain a  `userCtx`, and then use that to decide whether read access is allowed. Looking through `pouchdb-authentication` code, I couldn't find an immediately obvious way to do this, however.

**Comment by nolanlawson** [comment]
`pouchdb-authentication` is just a sugar API for doing AJAX requests against a CouchDB or PouchDB Server. If you want to implement a couch-per-user-esque functionality, you would definitely have to do it inside of express-pouchdb.

However you may find that it's easier to use a general-purpose tool that works against either CouchDB or PouchDB Server, such as [this Python project](https://github.com/ocasta/CouchDB-Selfservice).

**Comment by bguiz** [comment]
I am not looking to do a couch-per-user approach - more like a single couch, but have every GET request need to pass through a custom filter function. An express middleware such as the one I have created above, seems like a good place to do this.

Is there any way for me to obtain the `userCtx` based on the GET requests received by `express-pouchdb`?

**Comment by nolanlawson** [comment]
No, I don't think there's currently a way to get the userCtx via middleware.

**Comment by marten-de-vries** [comment]
Try ``req.couchSession``. But: that's not part of the documented API, so no guarantees it won't change in future versions.

**Comment by nolanlawson** [comment]
Closing as we will probably not support this explicitly
