### ISSUE TITLE
Move modules to pouchdb org

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/express-pouchdb#232]
@marten-de-vries I really appreciate the modularization you've done with PouchDB Server, but it's a bit difficult to collaborate because most of those modules are [on Bazaar](https://pythonhosted.org/Python-PouchDB/js-plugins.html). It would be a bit easier for the community if those modules were under the pouchdb organization, like express-pouchdb and pouchdb-server.

(I know I know, Github is a total monoculture these days, and it's a shame we took something beautiful and decentralized like Git and centralized it, but this just seems to be the way OSS is done nowadays, sadly. :stuck_out_tongue:)

Any chance of moving them over here? Also as a first step, it would be helpful to add me and daleharvey as npm owners, so that we can at least publish that way. :)

**Comment by gr2m** [comment]
That would be awesome! I'd be more than happy to help with the migration!

**Comment by nickcolley** [comment]
:+1: so many good projects! Willing to help out any doc changes etc :)

**Comment by marten-de-vries** [comment]
I already switched the Launchpad project to git, but I can see that's still a too large threshold. I'll start moving them to github. As for adding others as npm authors, that should've happened long ago. On that too.

**Comment by marten-de-vries** [comment]
The todo list. PRs welcome for documentation & test suite as soon as that's possible:

On Github
========

- [x] couchdb-eval
- [ ] couchdb-objects
- [ ] couchdb-render
- [ ] couchdb-resp-completer
- [ ] header-case-normalizer
- [ ] pouchdb-auth
- [ ] pouchdb-bulkdocs-wrapper
- [ ] pouchdb-changeslike-wrapper
- [ ] pouchdb-list
- [ ] pouchdb-plugin-error
- [ ] pouchdb-replicator
- [ ] pouchdb-req-http-query
- [ ] pouchdb-rewrite
- [ ] pouchdb-route
- [ ] pouchdb-seamless-auth
- [ ] pouchdb-security
- [ ] pouchdb-show
- [ ] pouchdb-system-db
- [ ] pouchdb-update
- [ ] pouchdb-validation
- [ ] pouchdb-vhost
- [ ] pouchdb-wrappers
- [ ] promise-nodify

In pouchdb org & npm rights
=======================

- [x] couchdb-eval
- [ ] couchdb-objects
- [ ] couchdb-render
- [ ] couchdb-resp-completer
- [ ] pouchdb-auth
- [ ] pouchdb-bulkdocs-wrapper
- [ ] pouchdb-changeslike-wrapper
- [ ] pouchdb-list
- [ ] pouchdb-plugin-error
- [ ] pouchdb-replicator
- [ ] pouchdb-req-http-query
- [ ] pouchdb-rewrite
- [ ] pouchdb-route
- [ ] pouchdb-seamless-auth
- [ ] pouchdb-security
- [ ] pouchdb-show
- [ ] pouchdb-system-db
- [ ] pouchdb-update
- [ ] pouchdb-validation
- [ ] pouchdb-vhost
- [ ] pouchdb-wrappers

Documentation rst -> markdown and inside README.md
=============================================

Documentation currently in: https://git.launchpad.net/python-pouchdb/tree/docs/js-plugins.rst?id=d5a4a276dca41b36231dc3a569213931125ff4e5

- [ ] pouchdb-auth
- [ ] pouchdb-list
- [ ] pouchdb-replicator
- [ ] pouchdb-rewrite
- [ ] pouchdb-seamless-auth
- [ ] pouchdb-security
- [ ] pouchdb-show
- [ ] pouchdb-update
- [ ] pouchdb-validation
- [ ] pouchdb-vhost

Tests Python -> JS
===============

Tests currently in: https://git.launchpad.net/python-pouchdb/tree/pouchdb/tests/plugins.py?id=d5a4a276dca41b36231dc3a569213931125ff4e5

- [ ] pouchdb-auth
- [ ] pouchdb-list
- [ ] pouchdb-replicator
- [ ] pouchdb-rewrite
- [ ] pouchdb-seamless-auth
- [ ] pouchdb-security
- [ ] pouchdb-show
- [ ] pouchdb-update
- [ ] pouchdb-validation
- [ ] pouchdb-vhost

**Comment by nolanlawson** [comment]
Thanks a lot @marten-de-vries; awesome work and love the transparency about everything you're doing. :)

**Comment by marten-de-vries** [comment]
Ok, first step of the migration is done. Now it's just making the projects more github-friendly. I.e., moving docs to README.md files, porting tests to JS, enabling Travis, adding Travis + dependency monitor badges, etc.

**Comment by gr2m** [comment]
@marten-de-vries thanks so much, this is awesome!

**Comment by gr2m** [comment]
@marten-de-vries let me know if I can help with the tests. I can also setup [semantic-release](http://github.com/semantic-release/semantic-release) if you are interested, that would mean that new releases get published automatically, based on very simple git message conventions, and it would also automatically create git tags & releases with changelogs. We are doing it all over Hoodie right now and are very happy with it. It's really, really cool, worth checking out if you haven't yet

**Comment by marten-de-vries** [comment]
Never used ``semantic-release`` before, but it looks handy. Help with moving the docs + tests would certainly be welcome. I'm wondering though if it's worth it to make some kind of npm package that shares most of the test infrastructure of all these new modules, so we don't have to copy/paste files all the time.

package.json's would become something like:
```javascript
"script": {
  "test": "./node_modules/.bin/pouchdb-plugin-helper test",
   ...
},
"devDependencies": {
  "pouchdb-plugin-helper": "^1.0.0"
  // no other dependencies necessary
}
```

etc. All coverage, test & jshint config could then stay in one place. Additional commands could be ``install-travis-file`` to copy the 'master' travis file directly into the current project, etc. Maybe a ``bages-code`` command to generate travis/david-dm badges for in README.md, etc. Probably worth the time it takes to write it for such a bunch of projects. Also, it could be reused for new plugins.

**Comment by gr2m** [comment]
For "jshint config", or solution at Hoodie is to try to avoid config files whenever possible, which is why we now use https://www.npmjs.com/package/standard everywhere. It's really cool once you get used to its conventions, it's just another thing you can stop thinking about :)

For the `.travis` bit, [semantic-release-cli](https://github.com/semantic-release/semantic-release#setup) sets it up for you, with a quick wizzard. It's really cool :) 

And for the badges, yeah, you could write a tool :) But you could also setup one repo with clear commit messages, and then ask for help, so you don't need to do it all on your own. People like me would take the opportunity to get involved into a project with simple things like that :)

**Comment by nolanlawson** [comment]
> I'm wondering though if it's worth it to make some kind of npm package that shares most of the test infrastructure of all these new modules, so we don't have to copy/paste files all the time.

I was actually looking into @bahmutov's [dont-break](https://github.com/bahmutov/dont-break) recently in order to fix this. Seems doable, although there's one bug that needs to be fixed first, which is caused by leveldown being slow as molasses to download: https://github.com/bahmutov/dont-break/issues/26

**Comment by marten-de-vries** [comment]
@nolanlawson ``dont-break``  seems interesting too, but what I meant was (for a start) just not having to replicate the whole istanbul/mocha/chai/pouchdb config all the time.

Since I also want ES7 async/await in the tests to make porting from Python easier, I went ahead and started doing exactly that today. Should be able to publish that soon.

**Comment by nolanlawson** [comment]
@marten-de-vries that's pretty neat; I love async/await. :) Also yeah, `standard` looks nice and I'll probably use it for my next project, but I'm not in a hurry to upgrade existing projects.

As for `dont-break`, it indeed allows us to avoid replicating the entire testing setup of a target dependent; it just `npm install`s the dependent, links your project to that project, and then runs that project's tests.

**Comment by marten-de-vries** [comment]
https://github.com/pouchdb/pouchdb-plugin-helper ; it's incomplete and probably not flexible enough to support at least every module I moved to github as part of this PR, but it's good enough for a 0.1.0 release & to be used by ``pouchdb-auth`` (Which I'm planning to push next, as soon as I figure an initial Travis + semantic-release setup out). Afterwards, the whole infrastructure is ready and the porting can begin.

**Comment by marten-de-vries** [comment]
I just pushed ``pouchdb-auth``'s [tests](https://github.com/pouchdb/pouchdb-auth/tree/master/test) to Github. It should be a good example on how to port tests for the remaining modules. Any help is welcome! I didn't yet set up ``semantic-release``, but that shouldn't be hard to add in the future.

**Comment by nolanlawson** [comment]
This is mostly done, I'm happy to close this issue. Thanks @marten-de-vries !

**Comment by marten-de-vries** [comment]
I'm working on this again this week, so I'm opening it again to make bookkeeping easier. I'll re-close it if I stop working on it again for a longer period.

If anyone wants to help, either adopt one of the PR(s) below (relatively easy because the 'hard' stuff is already done), or pick a project as described above and completely port it yourself (harder).
- https://github.com/pouchdb/pouchdb-security/pull/5

If no one helps, it'll be finished as well, it'll just take a bit longer. ;)

**Comment by gr2m** [comment]
Thanks @marten-de-vries! I’m heads down on shipping Hoodie, otherwise I’d help myself, but I’ll spread the word, maybe someone else finds time to help

**Comment by marten-de-vries** [comment]
All the relevant Python code has now been ported. That leaves updating documentation.

**Comment by gr2m** [comment]
:clap:

**Comment by marten-de-vries** [comment]
Reclosing this issue. I'm going to merge the WIP PRs, then open follow up issues for the docs. Seeing raw reStructuredText in the README file is still an improvement over the current files, and it might add some urgency to porting that over anyway, which would not be a bad thing.
