### ISSUE TITLE
GETting a user's document as the user returns a 404 missing

### ISSUE THREAD

**Issue by tyler-johnson** [pouchdb/express-pouchdb#240]
With CouchDB, If I have a user in my database, I can query their user document with their credentials:

    $ curl http://localhost:5984/_users/org.couchdb.user:test -u test:test
    {"_id":"org.couchdb.user:test", ...

In express-pouchdb this returns a 404 missing:

    $ curl http://localhost:3000/_users/org.couchdb.user:test -u test:test
    {"error":"not_found","reason":"missing"}

**Comment by nolanlawson** [comment]
Yup, this bug has been confirmed in pouchdb/pouchdb-server#101

**Comment by gr2m** [comment]
DELETing a `_users` is also affected

**Comment by gr2m** [comment]
Also probably relaeted: when `PUT`ing a users doc if it already exists, PouchDB Server returns a 403 with

```json
{"error":"forbidden","reason":"You may only update your own user document."}
```

while CouchDB returns a 409 wtih

```json
{"error":"conflict","reason":"Document update conflict."}
```

**Comment by marten-de-vries** [comment]
@gr2m I can imagine DELETE going wrong, but are you sure the session was the same in PouchDB and CouchDB for the second? (Including registered admins & users.)
