### ISSUE TITLE
Unable to replicate using Fauxton

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/express-pouchdb#247]
See screenshot. Looks like we didn't implement `POST /_replicate` correctly.

![screenshot from 2015-08-24 09 13 13](https://cloud.githubusercontent.com/assets/283842/9440852/647e5dbc-4a40-11e5-8138-708d3d6bf037.png)

**Comment by marten-de-vries** [comment]
I can only reproduce with skimdb. Replicating a local db from CouchDB (:5984) to PouchDB Server (:5985) works fine. Still, this should just work.

**Comment by nolanlawson** [comment]
Yeah, I used skimdb too.

**Comment by nolanlawson** [comment]
I can confirm that this is a PouchDB core issue. If you do:

```js
var PouchDB = require('pouchdb');
var db = new PouchDB('http://skimdb.iriscouch.com/registry');
db.info().then(console.log).catch(console.log);
```

You'll see:

```
{ [Error: ETIMEDOUT] status: 400 }
```

**Comment by nolanlawson** [comment]
fixed by https://github.com/pouchdb/pouchdb/commit/0cbb9f1d4890f4850c6a831bd4fa82d38b71cb56, will be resolved in the next pouchdb release
