### ISSUE TITLE
Do whatever it takes to get rid of PouchDB.destroy() in PouchDB

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/express-pouchdb#250]
Currently the only thing blocking https://github.com/pouchdb/pouchdb/pull/4223 is that apparently pouchdb-server breaks if you remove `PouchDB.destroy()`. Would love to get rid of this thing once and for all, or push back if it's not possible for some reason.

Related: https://github.com/pouchdb/express-pouchdb/pull/231

**Comment by marten-de-vries** [comment]
Just tried this out because I thought it should just work. Anyway, seems like there's a bug in ``pouchdb-wrappers``. Working on a fix, and a PR for ``express-pouchdb`` with the few changes necessary there.

**Comment by marten-de-vries** [comment]
Oh, also amended the title: we **need** ``PouchDB.destroy()`` in express-pouchdb as described in #231. But that can be handled by pouchdb-wrappers just fine, it makes total sense to get rid of it in pouchdb itself.

**Comment by nolanlawson** [comment]
fixed by 3fb9af1c15b2b1a55234b684c8f4de1140dfafbf
