### ISSUE TITLE
Idea: Add (NodeJS only) PouchDb adapters for common SQL engines

### ISSUE THREAD

**Issue by tohagan** [pouchdb/express-pouchdb#261]
You could clone the existing 'websql' adapter to implement new adaptors for MySQL, Prostgres, SQL Server, Oracle SQL dialects. They could share a common base classes with derived classes to implement overrides for SQL dialects. Alternatively, you could also use a NodeJS ORM as a less efficient bridge to these dialects.

I often export a subset of mobile data from an SQL engine into CouchDb so it can be replicated into PouchDb. Simpler would be to maintain a single SQL engine as backing store for an express pouchdb server. Now I'd only need to backup and administer a single database server. 
- Would be interesting to compare the performance to CouchDb.

As a code reference, here's an open source project that implements SQL dialects (implements portable migrations in C#):
- https://github.com/schambers/fluentmigrator/tree/master/src/FluentMigrator.Runner/Generators

**Comment by nolanlawson** [comment]
Right now the WebSQL adapter is very tightly tuned to SQLite. (E.g. it tries to read from the `sqlite_master` table.) It could run in Node.js, but somebody would have to write a WebSQL shim over SQLite3, which would be an interesting exercise, but I haven't seen anybody else take it up.

As is, you can use PouchDB over any *down database (e.g. SQLdown, MySQLdown, see http://pouchdb.com/adapters.html#pouchdb_in_node_js), but in my experience the performance is poor and the *down adapters themselves are buggy.

Currently even our MemDOWN adapter is slower than CouchDB for some cases, so my hunch is also that even a SQLite3 version of the WebSQL adapter would probably be slower. CouchDB has been performance-tuned over the past 10 years; PouchDB still has work to do in core JavaScript stuff to get our server-side performance up to snuff.

**Comment by tohagan** [comment]
Thanks for the feedback @nolanlawson . Yes ... I'm not surprised by the performance issues.
I thought I'd just throw the idea out there - even if it belonged on a much long term road map.
I have not urgent or compelling reason to replace the real CouchDb.

**Comment by nolanlawson** [comment]
Closing for now, please reopen as necessary
