### ISSUE TITLE
httpd authentication_handlers config not working

### ISSUE THREAD

**Issue by mciparelli** [pouchdb/express-pouchdb#263]
I have set 
```json
  "httpd": {
  "authentication_handlers": "{couch_httpd_oauth, oauth_authentication_handler}, {couch_httpd_auth, default_authentication_handler}, {couch_httpd_auth, cookie_authentication_handler}"
}
```
but it doesn't look like it's using basic auth before cookie auth. Am I setting this value wrongly?

**Comment by marten-de-vries** [comment]
We don't support that setting: express-pouchdb currently only supports the default couchdb configuration, and even then some things are missing (oauth is the biggest point there). If you want to give implementing it a shot, help is always welcome!

**Comment by mciparelli** [comment]
Hmm, I see, alright then. Thanks. Don't have time currently to implement that but it's good to know why it doesn't work.
