### ISSUE TITLE
Implement /_active_tasks

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/express-pouchdb#266]
Right now if you start a continuous replication in the Fauxton UI it will work, but you won't see any ongoing replications in the "active tasks" tab. It would be a lot nicer if this actually worked.

The way CouchDB works is that you can create ongoing replications that are in the `_replicator` database, and it will ensure that two DBs always stay in sync. This would be a killer feature for PouchDb Server.

See https://github.com/pouchdb/express-pouchdb/pull/265 for discussion and a TODO that I added to the source code.

**Comment by nolanlawson** [comment]
I suppose the "active tasks" and "_replicator database" might technically be two separate issues. (I guess you can have an ongoing replication that *isn't* defined in the _replicator database?) But it would be nice to fix both.

**Comment by marten-de-vries** [comment]
_replicator is there already. Renaming this issue.

**Comment by nolanlawson** [comment]
Thanks, thought I might have made that mistake.

**Comment by nolanlawson** [comment]
This issue was moved to pouchdb/pouchdb-server#182
