### ISSUE TITLE
encodeURIComponent causing duplicate databases

### ISSUE THREAD

**Issue by tyler-johnson** [pouchdb/express-pouchdb#274]
My express-pouchdb is duplicating databases due to the `encodeURIComponent()` on this line: https://github.com/pouchdb/express-pouchdb/blob/f4851a1a1dc15a31b62abd9b01f19c6befd444b5/lib/utils.js#L74

Here are the steps to replicate the issue:

1. Create a PouchDB class with `var MemPouch = PouchDB.defaults({ db: require("memdown") })`
2. Setup express-pouchdb on an express app: `app.use(require("express-pouchdb")(MemPouch));`
3. Create a database in code to use and edit in code, but with special url-encodable characters: `var db = new MemPouch("my/database");`
4. Access the database via HTTP: `http://localhost:3000/my%2Fdatabase`

From what I can tell, the leveldown adapter does not encode names and since my names are not going in originally encoded express-pouchdb duplicates them as they are two different names (`my/database` vs `my%2Fdatabase`). If I had to guess, that `encodeURIComponent()` is setup for the http adapter, but honestly it feels unnecessary as encoding the name should be the adapter's responsibility.

Mostly looking for feedback on how to solve this. Thanks!

**Comment by tyler-johnson** [comment]
Also this is what `/all_dbs` outputs after the duplication: 
![screenshot_43](https://cloud.githubusercontent.com/assets/310038/12468852/6a1d4ec0-bfa4-11e5-8204-cb6796187195.png)

Notice that there are two databases with the same name, but actually one is the encoded version and one is not.

**Comment by marten-de-vries** [comment]
It could very well be that that was added in a time PouchDB didn't handle encoding completely correct itself. Should be easy to test: removing the ``encodeURIComponent()`` there (and also in other locations?), then run the test suite (the pouchdb one).

If that and some manual testing using curl passes, it's probably good enough to ship. If not, then we at least now why that encode is there and where to fix it.

**Comment by tyler-johnson** [comment]
Okay so I tried it out without the `encodeURIComponent()` and while it solves the issue for the memdown backend, it creates issues for the normal leveldown backend. It seems like the leveldb adapter does not encode names by default and the leveldown backend will not create deep folders, so using a name like `my/database` breaks for that backend with a `[OpenError: IO error: /data/my/database/LOCK: No such file or directory]`.

Perhaps the leveldb adapter should be doing the encoding of the name to prevent discrepancies among backends? Have the encode in that particular spot is worrisome as this also leaks to the other Pouchdb adapters. I assume that when `express-pouchdb` is used with an HTTP adapter all the database names are double encoded over the network, resulting in encoded database names within CouchDB.

**Comment by marten-de-vries** [comment]
That's probably the original reason this was included. If you could get that recognised as an upstream bug that would definitely work, but it would complicate their code for little gain from their perspective so I'm not holding my breath for that.

Alternatively, you could argue that a db name is actually not supposed to contain a '/' and that you always have to encode it (you do need to do it for http, and apparently leveldown, anyway). In that case, it might be nice to have the PouchDB contructor throw an error if a non-urlencoded name is passed in or to auto-urlencode always, both would be breaking changes and in both cases I don't fully know the repercussions.

We could also just leave it the way it is, with you changing your ``var db = new MemPouch("my/database");`` line into ``var db = new MemPouch("my%2Fdatabase");``.

**Comment by gr2m** [comment]
I run into a similar problem with it myself, but for me a database with the name `user/abc4567` created `user%@F4567` while if I just use `new PouchDB('user/abc4567')` it creates the `user` folder and then the `abc4567` folder inside it.

The fact that the leveldb adapter throws an OpenError is in my opinion an issue of `pouchdb-adapter-leveldb` and I opened an Issue with a workaround here: https://github.com/pouchdb/pouchdb/issues/5668

I’ll start a pull request for this. I would consider releasing a new version with a breaking change as it might break existing applications that have the leveldb databases in the wrong paths now

**Comment by gr2m** [comment]
I started a PR, and I released a fork with it merged on npm if you want to give it a try: https://www.npmjs.com/package/@gr2m/express-pouchdb
