### ISSUE TITLE
'pouchdb' dependency from Github is failing

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/express-pouchdb#276]
Seems to be caused by the recent Rollup changes, but this is breaking all our builds, here and in pouchdb-server.

**Comment by nolanlawson** [comment]
Ugggh, this is an existing limitation of npm: https://github.com/npm/npm/issues/3055

**Comment by marten-de-vries** [comment]
Fixed per https://github.com/pouchdb/express-pouchdb/pull/277 . Keeping this open until it's fixed in npm **and** that version of npm is mainstream is long enough to not bother keeping the bug report over, in my opinion.
