### ISSUE TITLE
upgrade pouchdb-find dependency

### ISSUE THREAD

**Issue by kidwm** [pouchdb/express-pouchdb#287]
version 0.1.0 is too old and it introduces jshint and other dev tool as dependency.

Please upgrade it to 0.9.0 or latest version.

**Comment by marten-de-vries** [comment]
Thanks for your bug report.

Maybe we should just enable [greenkeeper](http://greenkeeper.io/) on this repo too, and be done with it?

**Comment by kidwm** [comment]
@marten-de-vries Thanks for reply!
@nolanlawson My npm version is 3.6.0 and I don't know why install `express-pouchdb` will also install `jshint` introduced by `pouchdb-find`:
```
npm ls jshint
project@0.0.1 /Users/user/Projects/project
└─┬ express-pouchdb@1.0.2
  └─┬ pouchdb-find@0.1.0
    └── jshint@2.9.1
```

**Comment by gr2m** [comment]
@marten-de-vries let me know if you have any questions or need help with greenkeeper :) But it should be very straight forward and resolve the outdated dependency issue for good :+1:

**Comment by marten-de-vries** [comment]
```
marten@procyon:~/git/express-pouchdb$ greenkeeper enable
info enable The GitHub slug is: pouchdb/express-pouchdb
pouchdb/express-pouchdb enabled
marten@procyon:~/git/express-pouchdb$ 
```

Let's see...

**Comment by garrensmith** [comment]
Closing since the latest pouchdb-find is working.
