### ISSUE TITLE
Fauxton navigation breaks when run as non-root

### ISSUE THREAD

**Issue by ekoome** [pouchdb/express-pouchdb#290]
I'm trying to navigate on Fauxton UI (e.g show databases, show config etc) but i get blank screen with the url redirected as follows.

Initial request:
http://localhost:3000/db/_utils/#/_all_dbs

This is redirected to be:

http://localhost:3000/db/_utils/#login?urlback=/_all_dbs

Do this have to do on authentication? Tried to click on login link but I get redirected to http://localhost:3000/db/_utils/#login?urlback=login

Here's my app:

```
var express = require ('express');
var app = express();
var PouchDB = require('pouchdb');
var riakdown = require('riakdown');

app.use('/db', require('express-pouchdb')(PouchDB));
var db = new PouchDB('acl', {db : riakdown, prefix: 'riak://localhost:8087/'});

app.listen(3000);
```

What am i missing?

**Comment by nolanlawson** [comment]
I think the issue here is that Fauxton is not designed to run anywhere except for the root. So the fact that you have a `/db` in there is causing it to fail.

What this issue indicates is that we should probably update Fauxton, because apparently [they fixed it recently](https://issues.apache.org/jira/browse/COUCHDB-1937) but we haven't updated since then.

**Comment by deckikwok** [comment]
hmm when will this be updated(fixed)?

**Comment by jure** [comment]
Hmm, I upgraded to the latest fauxton in https://github.com/jure/express-pouchdb/commits/upgrade_fauxton and I'm still getting this behaviour. I.e. navigation on Fauxton doesn't work. Sure, this is all fixable, but it's getting to a point where running a separate pouchdb-server on a different port, but using root paths for everything, is much more elegant and might be the best solution for most people (without digging into Fauxton).

**Comment by jure** [comment]
Any ideas from people more familiar with Fauxton? Perhaps this navigation issue is more of a Fauxton bug, but I find it surprising that no one is having issues with express-pouchdb's Fauxton under non-root paths? Perhaps it's something else that's causing this? Or just that nobody is using Fauxton :)

**Comment by DTrejo** [comment]
Here is a fix for this, it works for me. I will leave it as an exercise to the reader to clean up the code. Hope this helps!

```js
var PORT = 3000
var DB_URL = '/db'

return main()

function main() {
  readCSVs()

  app.use(DB_URL, require('express-pouchdb')(PouchDB))
  console.log('http://localhost:%s', PORT)
  console.log()

  var mountedPouch = null
  var stack = app._router.stack
  for (var i = 0; i < stack.length; i++) {
    var route = stack[i]
    // not sure how dependable this check is.
    if (route.name === 'mounted_app' && route.regexp.test(DB_URL)) {
      mountedPouch = route
      break
    }
  }
  // console.log(mountedPouch)

  // handles requests to e.g. '/_session' '/_all_dbs' '/_users' '/_users'
  app.use(function fauxtonIntercept(req, res, next) {
    // e.g. http://localhost:3000/db/_utils/
    var referer = url.parse(req.header('Referer'))
    if (0 === referer.pathname.indexOf(path.join(DB_URL, '/_utils/'))) {
      return mountedPouch.handle(req, res)
    }
    return next()
  })

  app.listen(PORT)
}
```

**Comment by bensleveritt** [comment]
I'm surprised more people don't encounter it considering this is the [first example usage of `express-pouchdb`](https://github.com/pouchdb/express-pouchdb#example-usage).

An official fix would be cool.

**Comment by jwickens** [comment]
Here's my version of @DTrejo fix, thanks for this! Btw in order to officially fix this the client would have to be rebuilt. You could build a fauxton client yourself but that seems more work than intercepting as @DTrejo is doing. I think the docs should definitely be updated though.

```js
const express = require('express');
const app = express();
const PouchDB = require('pouchdb');
const pouchRouter = require('express-pouchdb');
const path = require('path')
const url = require('url')

const PORT = process.env.PORT || 3000;
const DB_URL = '/db';
const pouchHandle = pouchRouter(PouchDB);
const fauxtonIntercept = (req, res, next) => {
    let referer = req.header('Referer');
    if (!referer) return next();

    let parsed = url.parse(referer);
    if (0 === parsed.pathname.indexOf(path.join(DB_URL, '/_utils/'))) {
      return pouchHandle(req, res);
    }
    return next();
};

app.use(DB_URL, pouchHandle);
app.use(fauxtonIntercept);

app.listen(PORT);
console.log(`app listening on ${PORT}`);
```

**Comment by nolanlawson** [comment]
This issue was moved to pouchdb/pouchdb-server#183

**Comment by michael-ts** [comment]
@jwickens I have tried this on my server and now /db/utils/#/_all_dbs (or for that matter, various other things after the '#/' or nothing at all) brings up a page with green buttons on the left "Databases", "Active Tasks", "Configuration", "Replication" as well as gray buttons "Documentation", "Login", and "Verify" and a logo next to "pouchdb server" at the botton left.  But to the right of that is a big blank area.  Nothing happens when I click on any of the buttons, although the hash portion of the URL changes.

Am I on the right track?  Any tips on how I might debug this?
