### ISSUE TITLE
user password not getting hashed on _bulk_docs request

### ISSUE THREAD

**Issue by tyler-johnson** [pouchdb/express-pouchdb#297]
The following request creates a user document with an actual `password` field instead of hashing the password and replacing it with the `derived_key`, `salt`, `iterations`, and `password_scheme` fields.

```sh
curl -X "POST" "http://localhost:3000/_users/_bulk_docs" \
	-H "Content-Type: application/json" \
	-d "{\"docs\":[{\"_id\":\"org.couchdb.user:testuser\",\"name\":\"testuser\",\"password\":\"test\",\"type\":\"user\",\"roles\":[]}]}"
```

This is unfortunate because it seems like PouchDB's `put()` method uses the `_bulk_docs` endpoint.

**Comment by nolanlawson** [comment]
Yikes, that is a pretty big bug on our part. Probably a bug in https://github.com/pouchdb/pouchdb-auth though.

**Comment by tyler-johnson** [comment]
Should I open an issue there as well?

**Comment by nolanlawson** [comment]
Nah let's wait for @marten-de-vries to confirm where the bug is.

**Comment by marten-de-vries** [comment]
It's a pouchdb-auth bug, working on a fix...

**Comment by marten-de-vries** [comment]
PR: https://github.com/pouchdb/pouchdb-auth/pull/9

**Comment by marten-de-vries** [comment]
Just released a new patch release for pouchdb-auth including that fix, so running 'npm update' should fix it for your app.

**Comment by tyler-johnson** [comment]
:+1:  Works great, thanks!
