### ISSUE TITLE
live replication:  Database encountered an unknown error, status=0 response

### ISSUE THREAD

**Issue by schamp** [pouchdb/express-pouchdb#300]
I have an express-pouchdb app mounted at /db in my express application:
in db.js:

```
const express = require('express')
const PouchDB = require('pouchdb')

const DB = PouchDB.defaults({
  prefix: './db/' // put all filesystem databases in the db subfolder
})

const expressPouch = require('express-pouchdb')

var app = express()
var pouchHandler = expressPouch(DB)
app.use('/', pouchHandler)

module.exports = app
```

main app:

```
app.use('/db', require('./db.js'))
```

I am using a database named 'sandbox' here, so in my client, I pass 'http://localhost:3000/db/sandbox' as the connection string.  I populated 'sandbox' by replicating a local couch server, but leaving that part out doesn't seem to affect the problem I'm having.

I have a pouchdb set up in the client to replicate the 'sandbox' database, like so:

```
  var db = new PouchDB('sandbox')
  var initialReplication = db.replicate.from(dbUrl, {})
  .on('error', function (err) {
    console.log('Error with initial replication', err)
  })

  initialReplication.then(function (result) {
    return db.replicate.from(dbUrl, {
      live: true,
      retry: true,
    }).on('error', function (err) {
      console.log('Error with db sync', err)
    })
  })
```

The initial replication works fine, but when I try to set up live sync, I get an error: 

```
CustomPouchError {
  status: 500,
  name: "unknown_error",
  message: "Database encountered an unknown error"
  error: true,
  result: ...
}
```

With retry on, the error seems to repeat based on the backoff rate and the timeout.

Digging into the interaction with the debugger, it appears that the XHR to the '_changes' route is failing with a status of 0, which gets built up into this error.  It appears that the request is being aborted due to a timeout, confirmed as best as I can by shortening and lengthening the timeout in the live replication options.  Increasing the timeout substantially does not appear to allow the _changes request time to complete, so I don't think it's just a matter of the timeout being too short.

That's as far as I've been able to dig so far.  I don't see anything unusual in the verbose logs of the express app.  Everything I've been able to find on XMLHttpRequest status = 0 is referring to a failed cross-origin request thing, but the rest of the replication calls work fine, so that doesn't seem like the culprit to me.

Am I missing something about how to use live replication?  Is there some constraint I'm not taking into account, or should this be working?

**Comment by schamp** [comment]
A few more notes:  When I point directly at a couchdb instance, the sync works fine.  I also appear to get the error if I try to attach to the db.changes({ live: true }) stream.

**Comment by schamp** [comment]
For the time being, my workaround is to use one-shot replication whenever I need to update (this may be what I want in the long-run anyway, as it's for an offline-first mobile app.  I may take a stab at creating a test to reveal this bug, it looked like perhaps there wasn't one covering this case.

**Comment by nolanlawson** [comment]
Please reopen if you can still reproduce, closing old issues...
