### ISSUE TITLE
feature request: graceful shutdown

### ISSUE THREAD

**Issue by cdaringe** [pouchdb/express-pouchdb#316]
hi all!

first, pouchdb-server/express-pouchdb/spawn-pouchdb-server are incredibly helpful for easily spinning up inmem integration test envs  as a couchdb mock.  so, as always, _thank you_!

in [spawn-pouchdb-server#41](https://github.com/hoodiehq/spawn-pouchdb-server/issues/41#issuecomment-220340841) i discuss how i believe the `pouchdb:changes` API still has outbound requests _after_ i cancel/destroy my pouch instance.  consequently, after my db destroys are complete, i transitively teardown express-pouchdb (which is in a child_process from spawn-pdbs).  trouble is, that INFLIGHT requests are still being processed, and 'hangups' or 'database closed' errors occur.

can we add hooks to shutdown gracefully?  i suggest maybe a `.on('SIGINT', ...)`. [express graceful ref](http://glynnbird.tumblr.com/post/54739664725/graceful-server-shutdown-with-nodejs-and-express)

im uncertain if an update would _also_ need to take place in pouchdb-server. would have to investigate more.  this is enough to get the discussion rolling!  thanks :)

**Comment by nolanlawson** [comment]
Hmmm... it's really hard to say here whether that should live in express-pouchdb or pouchdb-server. My gut feeling is that the cleanup code should be in pouchdb-server, since this is just an express component and probably shouldn't be responsible for SIGINT stuff.

**Comment by cdaringe** [comment]
yea, i was thinking about that as well. the reason i opted to file it here is because if it's done here (express-pouchdb), both packages can benefit from a graceful shutdown.  it would perhaps be a bummer if we did it pouchdb-server, then users here eventually wanted it.  i can't imagine anyone being disappointed about graceful shutdown, unless of course they had long running requests.  could be possibly be nested behind a flag on pdbs (`--graceful/-g`) and a simple config option here `{ graceful: true }`.  just thinkin out loud

**Comment by nolanlawson** [comment]
I think it's a useful feature, but maybe it should be exposed in a more Express-y way? In this case, the express-y way sort of feels like just documenting how to attach the proper event listeners on PouchDB in order to wait for a full shutdown.

In this case, it ought to be just as simple as:

```js
var replicate = db.replicate({live: true, retry: true, ...})
  .on('complete', function () {
    // I have shut down gracefully!
  });
replicate.cancel(); // cancel it
```

Same applies to `changes()`, `sync()`, etc. Notice though that we don't really know in advance which one users are using, so I don't think we can handle this within express-pouchdb at all, now that I think about it.

**Comment by cdaringe** [comment]
hey @nolanlawson!

if you are replicating with `live` (correct me if i'm wrong) then a 'complete' event never gets fired.

but regardless, the problem is that I don't have a way to shut down express gracefully to begin with.  so in your `.on('complete', ... )`, you assume, a graceful shutdown has happened, but that is in-and-of-itself that which I cannot guarantee.  i can stop the server, but not gracefully with the existing API.  if there is already an inflight request and i stop the server, the only place to catch the server teardown would be in a `.on('error', ...)`, handler, and i can't even guarantee that (because the request might _actually_ succeed!).  tricky, i know.

consider these steps:
- init remote db-server
- init local db
- init local-remote replication
- do some i/o and tests
- teardown local db
- teardown remote db-server

in this series of events, when i teardown the local-db, in pouch, there's no way for me in live mode to know if there are outbound http requests happening through the changes api. hence, i just `cancel` and `destroy`.  there still may very well be outbound requests.  when i go to teardown the remote db-server, i risk interrupting handling such a request, even if i don't care about it anymore!

what i do now to avoid that whole situation is simply `.cancel()` as you mention, however, i do a sloppy `setTimeout(..., 100)` to hope that any outbound HTTP requests have finished their cycle, and finally teardown the server after waiting a little bit.

does that clarify?  was it already clear?  sorry for the verbosity.

**Comment by nolanlawson** [comment]
mmm, I'm starting to see now. When you say "teardown," you mean `destroy()`, right? I know that race conditions with `destroy()` are an issue, but our previous stance has been that users need to clean up everything themselves before they `destroy()`.

If it's not the case, though, that `'complete'` only fires when everything is cleaned up, then I would consider that a bug in core PouchDB and not a bug in express-pouchdb/pouchdb-server.

**Comment by cdaringe** [comment]
What I meant by teardown was stopping the serve non-gracefully.  I'd be killing the server during an integration test because the test focuses on client code.  So, the replicating client does some work, I do some assertuons, then I kill the server. Unknown to me, the replicating client had outbound requests.  Thus, killing the server ended up being problematic, and the pouch client would explode with socket errors!  Hence, this issue is specifically targeted at live replicating, sync stuff.  :). Whoops, late to respond by a few months!  My timeout hack seems to be somewhat stable

**Comment by daleharvey** [comment]
We have had the same issue in the pouchdb tests, we solve it by 

```
it('does', function(done) { 
   var sync = db.sync(remote, {live: true});
   sync.on('complete', function() { done(); });
   .... test conditions
   sync.cancel();
});
```

The cancel operation itself is not synchronous, but `complete` will call once it is finished all processing

**Comment by cdaringe** [comment]
waaaat!  no kidding! i'll _try it, pronto_.

**Comment by cdaringe** [comment]
holy $h@t it worked!  yahoo!  [pouchy 10.1.+](https://github.com/cdaringe/pouchy/releases/tag/v10.1.0) now detects a live replicating db and waits for `complete` on `.destroy`.  thanks @daleharvey!

**Comment by cdaringe** [comment]
@daleharvey, do you know off-hand if this happens in the EE from `sync` _and_ `changes`?  I recall that there are a couple of emitters at play...

**Comment by cdaringe** [comment]
it does. yahtzee.
