### ISSUE TITLE
Throws warnings "Using a callback for new PouchDB()is deprecated."

### ISSUE THREAD

**Issue by olexme** [pouchdb/express-pouchdb#334]
Started to happen after PouchDB was upgraded to v5.4

**Comment by KRuelY** [comment]
This is due to the callback passed here:

https://github.com/pouchdb/express-pouchdb/blob/master/lib/utils.js#L74

**Comment by garrensmith** [comment]
This is fixed in #336

**Comment by garrensmith** [comment]
This is now fixed in master.
