### ISSUE TITLE
dependency node-uuid has security vulnerability

### ISSUE THREAD

**Issue by mohlsen** [pouchdb/express-pouchdb#352]
[node-uuid](https://github.com/broofa/node-uuid) v1.4.1, which the current express-pouchdb has a dependency on, has a security vulnerability.  See https://github.com/broofa/node-uuid/issues/122 and https://nodesecurity.io/advisories/93

We should update to the latest.

PR coming.

**Comment by nolanlawson** [comment]
Fixed in https://github.com/pouchdb/express-pouchdb/pull/353
