### ISSUE TITLE
Can’t configure DB file location

### ISSUE THREAD

**Issue by swashcap** [pouchdb/express-pouchdb#363]
OS: OS X 10.11.6
Node: v6.3.1
express-pouch: 1.0.7

Problem: I want to run an Express PouchDB server programmatically, in memory, for testing. Ideally, this does’t save _any_ files (see #303). In the mean time, it would be great to shove everything in a temporary directory and `rm -rf` it at the end of testing. Here’s my setup, which [closely mirrors pouchdb-server](https://github.com/pouchdb/pouchdb-server/blob/cf0a0280101ce313695101f1fb3eecf9e519db94/bin/pouchdb-server):

``` js
'use strict';

const express = require('express');
const expressPouchDB = require('express-pouchdb');
const memdown = require('memdown');
const path = require('path');
const PouchDB = require('pouchdb-node');

PouchDB.defaults({
  db: memdown,
  prefix: path.resolve(__dirname, '.tmp') + path.sep,
});

module.exports = function getPouchDBExpressApp() {
  const app = express();

  app.use('/', expressPouchDB(PouchDB));

  return app;
};
```

Unfortunately, database directories _aren’t saved to .tmp!_ Any thoughts?

**Comment by DQvsRA** [comment]
Just use:
POUCHDB.defaults(
{
    prefix: './db/'
});
And make sure that this folder exists.

**Comment by nolanlawson** [comment]
This issue was moved to pouchdb/pouchdb-server#189
